steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull southamerica-east1-docker.pkg.dev/${PROJECT_ID}/matriarca/frontend:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--cache-from', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/matriarca/frontend:latest',
    '--build-arg', 'NEXT_PUBLIC_API_URL=${_API_URL}',
    '--build-arg', 'NEXT_PUBLIC_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}',
    '--build-arg', 'NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${_GOOGLE_MAPS_API_KEY}',
    '-t', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/matriarca/frontend:latest',
    '.'
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'telemedicina-frontend'
  - '--image'
  - 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/matriarca/frontend:latest'
  - '--region'
  - 'southamerica-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
- 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/matriarca/frontend:latest'

